import "tailwindcss/dist/base.min.css"
import "tailwindcss/dist/components.min.css"
import "tailwindcss/dist/utilities.min.css"
import "typeface-bebas-neue"
import "typeface-montserrat"
import "./src/components/styles.css"
